
DROP TABLE IF EXISTS LEVEL;

CREATE TABLE LEVEL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  imageUrl VARCHAR(2500) NOT NULL,
  name VARCHAR(2500) NOT NULL,
  sourceLanguage VARCHAR(2500) NOT NULL,
  targetLanguage VARCHAR(2500) NOT NULL
);